services:
  runner:
    build: .
    volumes:
      # Use host creds
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/toy-cdk/cdk.out:/tmp/toy-cdk/cdk.out
#   entrypoint: [tail, -f, /dev/null]
